### ISSUE TITLE
Please help me out 

### ISSUE THREAD

**Issue by max4342** [logicallysound/streamdeck-discord-message#11]
hsy so i  Downloaded this and I can't find the stream d Deck plugin like What am I doing wrong because the plugin doesn't seem to be there it or at least whatever I need to run  For the stream  Dec. Software to recognize it 

To add it to the list ??? 

 I am a streamer myself and i really want to use this  Plug in

**Comment by logicallysound** [comment]
Are you sure you downloaded the release zip and not the code? The built streamdeck plugin file is not in the code tree, I build it and provide the zip file in Releases.

**Comment by max4342** [comment]
How do I download it

**Comment by logicallysound** [comment]
https://github.com/logicallysound/streamdeck-discord-message/releases/tag/v1.1.0

**Comment by logicallysound** [comment]
You want the zip file that isn't source code.

**Comment by logicallysound** [comment]
Going to call this closed since I've answered the question but if you need further clarification please feel free to follow up.
