### ISSUE TITLE
text will post, but no response happens from other bots when using commands.

### ISSUE THREAD

**Issue by ColdfireDI** [logicallysound/streamdeck-discord-message#15]
when using a commands that are supposed to call from another bot, theres no response. the text will post but there will be no response from other bots. so for example:

stream deck posts "-p lofi"
grovvy bot is supposed to respond and play music. instead nothing happens

if i myself do the command manually under my own account, it works fine. So if I specifically say -p lofi and dont use the stream deck, i can get the bot to respond. 

any ideas? here is an example of -rots command. only when i typed the command myself does it work

![Screenshot 2021-04-17 225448](https://user-images.githubusercontent.com/29430595/115132640-f86ef500-9fcf-11eb-8809-b8b9616d59a8.png)

**Comment by eabase** [comment]
probably Related to #7

**Comment by logicallysound** [comment]
Yes this is a known issue as a number of Discord bots will not parse messages being sent by other bot accounts and messages posted by webhooks are considered as coming from a bot account.

Yes, #7 is the canonical issue tracking this.
