### ISSUE TITLE
Can't send different pre configured messages within the same folder

### ISSUE THREAD

**Issue by ShadaxTheWizard** [logicallysound/streamdeck-discord-message#5]
My use case is pretty unique, but i wanted to set up folders to automatically send memes to one of my discord channels. Unfortunately i can't have multiple actions within the same folder, i.e when i create a new action (same webhook), but update the text, all the actions inside that folder now send that text

**Comment by cnschu** [comment]
fixed, waiting for merge.

**Comment by logicallysound** [comment]
I've merged this fix along with a few other things that cnschu sent. Thanks for the contribution! I'll build a new release of the plugin soon.
