### ISSUE TITLE
Cant seem to get it to work

### ISSUE THREAD

**Issue by autumnvondoe** [logicallysound/streamdeck-discord-message#9]
I put in the webhooks url on stream deck but when I press the discord button nothing happens not sure what I may have done wrong
![Annotation 2020-06-23 215622](https://user-images.githubusercontent.com/29993629/85488561-863ea700-b59c-11ea-9f1d-9fa588b9e63c.png)
It seems to only work if I copy the button to my stream deck homescreen, it doesnt want to work if the button is in a stream deck folder (unless like I said there is a copy on the stream deck home area)
Update: it seems to not matter if its on the homepage of the steam deck or not but it seems to only work if theres a copy of the button

**Comment by mediamanrit** [comment]
Try restarting the Stream Deck application.  I'm having a problem I just posted an Issue about where buttons only work after I restart the Stream Deck application.

**Comment by logicallysound** [comment]
Did restarting as suggested above work? Trying to triage the new bugs so I can do a bit of work on the weekend.

**Comment by kuhljeff** [comment]
I had the same issue after initial install but got it to work by restarting it. Also finding that I have to restart streamdeck anytime I make changes to or add a new one.

**Comment by cnschu** [comment]
>Also finding that I have to restart streamdeck anytime I make changes to or add a new one.

add a new what?

**Comment by cnschu** [comment]
> It seems to only work if I copy the button to my stream deck homescreen, it doesnt want to work if the button is in a stream deck folder (unless like I said there is a copy on the stream deck home area)
Update: it seems to not matter if its on the homepage of the steam deck or not but it seems to only work if theres a copy of the button

Have you tried the following?
1) completely empty the "webhook" field, 
2) copying the webhook anew from discord to the webhook field,
3) check that you don't have copied the webhook twice into the webhook field,
4) leaving the webhook field by pressing TAB

**Comment by logicallysound** [comment]
I think this issue was introduced when #8 was fixed. Somehow the plugin's settings per button don't get properly updated until the Stream Deck application is restarted. I'm going to try to fix this soon.

**Comment by logicallysound** [comment]
This should be fixed in the next release. Thanks for your patience, all.
